### ISSUE TITLE
Partial refresh can not write white pixels on top of black pixels.

### ISSUE THREAD

**Issue by SamuelBurnes** [phoreglad/pico-epaper#11]
In partial refresh mode, even with the pixel values stored correctly in _bw, the show method is unable to show white pixels. It draws all the black pixels of the image but does not alter where the white pixels were supposed to be.

**Comment by phoreglad** [comment]
Unfortunately, it's just how the partial refresh works. It was discussed in #10 and the proposed workaround is to draw black pixels first and then clear them to white.

**Comment by Cheddoleum** [comment]
The curious effect is that you can't overwrite blit-ed black pixels with white, but you can do it to drawn or text black pixels. Observe also the way this is demonstrated in the count-to-ten[ demo at the end of the "__main__ " function](https://github.com/phoreglad/pico-epaper/blob/66194a89f3d0798c92d13b12c9c6e09eab9eea35/Pico_ePaper.py#L595).

Simply drawing black with any of the draw instructions (rectangle, line or text) seems to allow a subsequent blit to clobber those pixels with white with blit, it's not necessary to also clear them to white first.

(If I may comment: It actually makes a kind of sense in order to support the four gray scales: you need to be able make two passes with different bit arrays and for this to work it's necessary for the white pixels to be ignored, and not overwrite existing black or gray pixels.  It's opaque how it distinguishes between "pixels that are black because they were drawn" vs "pixels that are black because they were blitted", but at a WAG it seems like that internally it "remembers" the blit'ed pixels for merging purposes, but "forgets" those pixels when they're drawn to.)

**Comment by phoreglad** [comment]
My working hypothesis is that when switching to the partial mode the driver "assumes" that all pixels were cleared. In this mode (that should really be called differential) only the changed pixels are actually refreshed, so trying to draw white pixels doesn't work as the driver "thinks" there's no change, regardless of what is left on the screen from working in normal mode. Unfortunately, I don't think there's anything I can do to work around it.

**Comment by julien123123** [comment]
I believe I resolved the issue. The IC controlling the Epd has two buffers. One for black and white and the other for red. Since there is no red in that version of the screen, It might be used for shades of grey in the normal mode. In the partial mode, the IC takes the 1s in the red buffer and turns them to white, and then takes the 1s in the black and white buffer and turns them to black. When you leave the screen on, and do a second partial update, it just takes what was on the black and white buffer and puts it in the red buffer so that remembers which pixels to erase.
I made an example showing my theory using the contents of the examples folder : https://gist.github.com/julien123123/9ec01d29f1dbf63ccfee3fc34e533984
If you want to do a 'reverse' partial update, you need to send the command 0x26, and then send the buffer containing the new white pixels as black ones, and then send the old image as normal with partial mode on.

Now, I'm wondering if it's possible to send smaller buffers to the IC instead of the gigantic bytearray everytime.

*** correction because I just had a glitch happen: Indeed, partial mode is a differential mode. The epd will turn pixels white ONLY if they are 1s in the red buffer, and are not 1s in the black and white buffer. It should not put new black over what's already black in the red buffer. That's why, if you don't have your red buffer sent properly, there might be ghosts in the image.
